import assert from 'node:assert/strict';
import {execFileSync,spawnSync,spawn} from 'node:child_process';
import {mkdir,mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('./',import.meta.url)),fixtures=join(root,'fixtures');
const schema=await readFile(join(fixtures,'full-schema.sql'),'utf8'),migration=await readFile(join(fixtures,'unread.sql'),'utf8');
const metadata=JSON.parse(await readFile(join(fixtures,'bindings.json'),'utf8'));
assert.equal(createHash('sha256').update(schema).digest('hex'),metadata.schema_sha256,'[proposal unread] Full schema fixture hash mismatch.');
assert.equal(createHash('sha256').update(migration).digest('hex'),metadata.unread.sql_sha256,'[proposal unread] SQL proposal fixture hash mismatch.');
const negativeScope=await readFile(join(fixtures,'unread-negative-private-scope.sql'),'utf8'),negativePrefix=await readFile(join(fixtures,'unread-negative-peer-prefix.sql'),'utf8');
for(const [name,value] of [['unread-negative-private-scope.sql',negativeScope],['unread-negative-peer-prefix.sql',negativePrefix]])assert.equal(createHash('sha256').update(value).digest('hex'),metadata.unread.negative_sql_sha256[name],'[proposal unread] Negative fixture hash mismatch.');
const reports=process.env.STABLEFLOW_REPLAY_REPORT_DIR||join(root,'reports');
await mkdir(reports,{recursive:true});
assert.equal(process.platform,'linux','[proposal unread] Runtime requires an isolated non-root Linux runner.');
const pgBin=process.env.STABLEFLOW_TEST_PG_BIN||spawnSync('pg_config',['--bindir'],{encoding:'utf8'}).stdout.trim();
assert.ok(process.getuid()!==0&&['initdb','pg_ctl','psql'].every(name=>existsSync(join(pgBin,name))));
const env=Object.fromEntries(Object.entries(process.env).filter(([key])=>!key.startsWith('PG')));
const directory=await mkdtemp(join(tmpdir(),'sf-unread-')),data=join(directory,'data'),socket=join(directory,'socket'),port='58502';
const command=(name,args,input)=>execFileSync(join(pgBin,name),args,{encoding:'utf8',input,env,timeout:30_000,stdio:['pipe','pipe','pipe']});
const connection=role=>['-h',socket,'-p',port,'-U',role,'-X','-qAt','-v','ON_ERROR_STOP=1','-v','VERBOSITY=verbose'];
const sql=(db,input,role=input.startsWith('set role ')?'sf_admin':'postgres')=>command('psql',[...connection(role),'-d',db],input).trim();
const uid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const A=uid(101),B=uid(102),C=uid(103),D=uid(104),S=uid(1),T=uid(2),PRIVATE=uid(201),GROUP=uid(202),FOREIGN=uid(203),LEGACY_PRIVATE=uid(204),FALSE_GROUP=uid(205);
const M1=uid(301),M2=uid(302),M3=uid(303),OWN=uid(304),NULL_AUTHOR=uid(305),BLOCKED=uid(306),OTHER=uid(307),GROUP_PEER=uid(308),OLD=uid(309);
const checks=[];let started=false;
const check=(name,run)=>{run();checks.push({name,result:'PASS'});};
const expectError=(db,input,code,text)=>{let failure;try{sql(db,input);}catch(error){failure=String(error.stderr);}assert.ok(failure?.includes(code)&&failure?.includes(text),`Expected ${code}/${text}; got ${failure||'success'}`);};
const as=(caller,expression)=>`set role authenticated;set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${caller}';${expression}`;
const idsSql=ids=>`array[${ids.map(id=>`'${id}'::uuid`).join(',')}]::uuid[]`;
const receipt=(db,caller,chat,ids,mode='own_chat_read_state',expected=caller)=>JSON.parse(sql(db,as(caller,`select public.${mode}('${expected}','${chat}',${idsSql(ids)});`)));
const reads=db=>sql(db,'select jsonb_agg(to_jsonb(r) order by user_id,message_id) from public.chat_message_reads r;');
const policies=db=>sql(db,"select jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname) from pg_policies p where schemaname in('public','storage');");
const grants=db=>sql(db,"select jsonb_agg(to_jsonb(t) order by table_schema,table_name,grantee,privilege_type) from information_schema.table_privileges t where table_schema in('public','storage') and table_name<>'chat_message_reads';");
const contents=db=>sql(db,"select jsonb_build_object('messages',(select jsonb_agg(to_jsonb(m) order by id) from public.messages m),'members',(select jsonb_agg(to_jsonb(c) order by id) from public.conversation_members c),'stables',(select jsonb_agg(to_jsonb(s) order by id) from public.stable_members s),'profiles',(select jsonb_agg(to_jsonb(p) order by id) from public.profiles p));");
const clone=db=>sql('postgres',`create database ${db} owner postgres template full_schema;`,'sf_admin');
const seed=db=>sql(db,`
insert into auth.users(id) values('${A}'),('${B}'),('${C}'),('${D}');
insert into public.stables(id,name,created_by) values('${S}','Synthetic stable','${A}'),('${T}','Other synthetic stable','${C}');
insert into public.stable_members(stable_id,user_id,role,access) values('${S}','${A}','rider','view'),('${S}','${B}','admin','owner'),('${T}','${C}','admin','owner');
insert into public.conversations(id,is_group,stable_id,created_by_user_id,title) values('${PRIVATE}',false,null,'${A}','Synthetic private'),('${GROUP}',true,'${S}','${A}','Synthetic group'),('${FOREIGN}',false,null,'${C}','Foreign private'),('${LEGACY_PRIVATE}',false,'${S}','${B}','Private requires cm'),('${FALSE_GROUP}',true,'${T}','${C}','Group requires stable');
insert into public.conversation_members(conversation_id,user_id) values('${PRIVATE}','${A}'),('${PRIVATE}','${B}'),('${FOREIGN}','${C}'),('${LEGACY_PRIVATE}','${B}'),('${FALSE_GROUP}','${A}');
insert into public.messages(id,conversation_id,author_id,text,created_at) values
('${M1}','${PRIVATE}','${B}','Peer first','2026-10-07 12:00:00Z'),('${M2}','${PRIVATE}','${B}','Peer same time','2026-10-07 12:00:00Z'),('${M3}','${PRIVATE}','${B}','Newer peer','2026-10-07 12:05:00Z'),('${OWN}','${PRIVATE}','${A}','Own','2026-10-07 12:00:00Z'),('${NULL_AUTHOR}','${PRIVATE}',null,'Unknown peer','2026-10-07 12:00:00Z'),('${BLOCKED}','${PRIVATE}','${D}','Blocked peer','2026-10-07 12:00:00Z'),('${OTHER}','${FOREIGN}','${C}','Foreign text','2026-10-07 12:00:00Z'),('${GROUP_PEER}','${GROUP}','${B}','Group peer','2026-10-07 12:00:00Z'),('${OLD}','${PRIVATE}','${B}','Old unloaded history','2025-10-07 12:00:00Z');
insert into public.blocked_users(blocker_user_id,blocked_user_id) values('${A}','${D}');
`,'sf_admin');
const report={state:'PROPOSED ONLY',source_head:metadata.source_head,schema_sha256:metadata.schema_sha256,migration_sha256:createHash('sha256').update(migration).digest('hex'),tcp_enabled:false,provider_requests:0,role_model:'postgres NOSUPERUSER BYPASSRLS owns public tables; Auth.users separate owner with SELECT-only to postgres',fixture_revision:metadata.unread.revision,negative_fixture_sha256:metadata.unread.negative_sql_sha256,driver_source_sha256:metadata.unread.source_driver_sha256,packaged_driver_sha256:createHash('sha256').update(await readFile(fileURLToPath(import.meta.url))).digest('hex'),jwt_model:'synthetic GUC claims, not signed JWT/PostgREST/Hosted acceptance',checks};
try{
 await mkdir(socket);command('initdb',['-D',data,'-U','sf_admin','--auth=trust','--no-locale','-E','UTF8']);command('pg_ctl',['-D',data,'-l',join(directory,'postgres.log'),'-o',`-k ${socket} -p ${port} -c listen_addresses=''`,'-w','start']);started=true;
 sql('postgres','create role postgres login superuser;','sf_admin');
 assert.equal(sql('postgres','show listen_addresses;'),'','[proposal unread] TCP must be disabled.');
 report.postgres_version=sql('postgres','show server_version;');
 sql('postgres','create role authenticated nologin;create role anon nologin;create role service_role nologin bypassrls;create database full_schema;');
 sql('full_schema',`create schema auth;create schema storage;create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}'::jsonb,deleted_at timestamptz,banned_until timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;create function auth.role() returns text language sql stable as $$select current_setting('request.jwt.claim.role',true)$$;create table storage.objects(id uuid primary key default gen_random_uuid(),owner uuid,owner_id text,bucket_id text);alter table storage.objects enable row level security;create policy storage_existing_select on storage.objects for select to authenticated using(auth.role()='authenticated');`);
 sql('full_schema',schema);
 sql('full_schema',`grant usage on schema public,auth,storage to authenticated,anon,service_role;grant select,insert,update,delete on all tables in schema public to authenticated;alter table auth.users owner to sf_admin;grant select on auth.users to postgres;`);
 sql('postgres','alter role postgres nosuperuser bypassrls;');
 clone('candidate');seed('candidate');
 const oldPolicies=policies('candidate'),oldGrants=grants('candidate'),oldContent=contents('candidate');
 check('ordinary migration role is NOSUPERUSER/BYPASSRLS with only SELECT on separately owned Auth table',()=>{assert.equal(sql('candidate',"select (not rolsuper) and rolbypassrls from pg_roles where rolname=current_user;"),'t');assert.equal(sql('candidate',"select has_table_privilege(current_user,'auth.users','SELECT') and not has_table_privilege(current_user,'auth.users','UPDATE');"),'t');});
 sql('candidate',migration);
 check('one new own table/two narrow RPCs; existing messages/content/ACLs/RLS/publications untouched',()=>{assert.equal(contents('candidate'),oldContent);assert.equal(policies('candidate'),oldPolicies);assert.equal(grants('candidate'),oldGrants);assert.equal(sql('candidate',"select count(*) from pg_publication;"),'0');assert.equal(sql('candidate',"select count(*) from public.chat_message_reads;"),'0');});
 check('authenticated/anon/service-role have no raw receipt SELECT/INSERT/UPDATE/DELETE and no anon/service RPC execution',()=>{for(const role of ['authenticated','anon','service_role'])for(const privilege of ['SELECT','INSERT','UPDATE','DELETE'])assert.equal(sql('candidate',`select has_table_privilege('${role}','public.chat_message_reads','${privilege}');`),'f');for(const role of ['anon','service_role'])expectError('candidate',`set role ${role};select public.own_chat_read_state('${A}','${PRIVATE}',array[]::uuid[]);`,'42501','permission denied');});
 check('JWT caller authority cannot be changed by expected UID argument or anon/missing claim',()=>{expectError('candidate',as(B,`select public.mark_chat_messages_read('${A}','${PRIVATE}',${idsSql([M1])});`),'42501','Verifierat eget konto');expectError('candidate',`set role authenticated;set request.jwt.claim.role='anon';set request.jwt.claim.sub='${A}';select public.own_chat_read_state('${A}','${PRIVATE}',array[]::uuid[]);`,'42501','Verifierat eget konto');expectError('candidate',`set role authenticated;set request.jwt.claim.role='authenticated';select public.own_chat_read_state('${A}','${PRIVATE}',array[]::uuid[]);`,'42501','Verifierat eget konto');assert.equal(sql('candidate','select count(*) from public.chat_message_reads;'),'0');});
 check('private access needs own current conversation_member even when broad baseline stable-OR-message RLS allows SELECT',()=>{expectError('candidate',as(A,`select public.own_chat_read_state('${A}','${LEGACY_PRIVATE}',array[]::uuid[]);`),'42501','Aktuell chattåtkomst');expectError('candidate',as(C,`select public.own_chat_read_state('${C}','${PRIVATE}',array[]::uuid[]);`),'42501','Aktuell chattåtkomst');});
 check('group access needs current stable membership; a conversation_member alone is insufficient',()=>{expectError('candidate',as(A,`select public.own_chat_read_state('${A}','${FALSE_GROUP}',array[]::uuid[]);`),'42501','Aktuell chattåtkomst');assert.deepEqual(receipt('candidate',A,GROUP,[]).unread_message_ids,[GROUP_PEER]);});
 check('complete own snapshot counts nullable author and all unloaded history; excludes own and currently blocked author',()=>{const r=receipt('candidate',A,PRIVATE,[M1,NULL_AUTHOR]);assert.equal(r.complete,true);assert.deepEqual(r.requested_message_ids,[M1,NULL_AUTHOR]);assert.deepEqual(r.read_message_ids,[]);assert.deepEqual(r.unread_message_ids,[M1,M2,M3,NULL_AUTHOR,OLD]);assert.deepEqual(Object.keys(r).sort(),['complete','conversation_id','known_read_message_ids','read_message_ids','requested_message_ids','unread_message_ids','user_id']);});
 check('exact observed subset is acknowledged, never same-time prefix, older unloaded prefix, own echo or unseen newer ID',()=>{const r=receipt('candidate',A,PRIVATE,[M1,NULL_AUTHOR], 'mark_chat_messages_read');assert.deepEqual(r.read_message_ids,[M1,NULL_AUTHOR]);assert.deepEqual(r.unread_message_ids,[M2,M3,OLD]);assert.equal(r.user_id,A);assert.equal(r.conversation_id,PRIVATE);});
 check('lost acknowledgement retry includes already-existing receipt IDs and does not rewrite original read timestamp',()=>{const before=reads('candidate'),r=receipt('candidate',A,PRIVATE,[NULL_AUTHOR,M1,M1],'mark_chat_messages_read');assert.equal(reads('candidate'),before);assert.deepEqual(r.read_message_ids,[M1,NULL_AUTHOR]);assert.deepEqual(r.requested_message_ids,[M1,NULL_AUTHOR]);});
 check('cross-chat, own-author, blocked, unknown, null and mixed batch all fail before any partial insert',()=>{const before=reads('candidate');for(const id of [OTHER,OWN,BLOCKED,uid(999)])expectError('candidate',as(A,`select public.mark_chat_messages_read('${A}','${PRIVATE}',${idsSql([M2,id])});`),'42501','Meddelandena kunde inte verifieras');expectError('candidate',as(A,`select public.mark_chat_messages_read('${A}','${PRIVATE}',null);`),'22023','Exakta meddelande');expectError('candidate',as(A,`select public.mark_chat_messages_read('${A}','${PRIVATE}',array[null]::uuid[]);`),'22023','Exakta meddelande');assert.equal(reads('candidate'),before);});
 check('two devices overlap/disjoint exact IDs; later own-state/reload resolves the same durable union',()=>{receipt('candidate',A,PRIVATE,[M1,M2],'mark_chat_messages_read');receipt('candidate',A,PRIVATE,[M2,M3],'mark_chat_messages_read');const r=receipt('candidate',A,PRIVATE,[M1,M2,M3,NULL_AUTHOR]);assert.deepEqual(r.read_message_ids,[M1,M2,M3,NULL_AUTHOR]);assert.deepEqual(r.unread_message_ids,[OLD]);});
 check('complete own known-read IDs cover already-read peers outside requested/loaded history and stay chat-scoped',()=>{receipt('candidate',A,GROUP,[GROUP_PEER],'mark_chat_messages_read');const r=receipt('candidate',A,PRIVATE,[OLD]);assert.deepEqual(r.read_message_ids,[]);assert.deepEqual(r.known_read_message_ids,[M1,M2,M3,NULL_AUTHOR]);assert.deepEqual(r.unread_message_ids,[OLD]);assert.equal(r.known_read_message_ids.includes(GROUP_PEER),false);assert.deepEqual(receipt('candidate',B,PRIVATE,[]).known_read_message_ids,[]);});
 check('read receipts are own-only; another caller retains its distinct unread/message read state',()=>{const r=receipt('candidate',B,PRIVATE,[OWN]);assert.deepEqual(r.read_message_ids,[]);assert.deepEqual(r.unread_message_ids,[OWN,NULL_AUTHOR,BLOCKED]);});
 check('new older/same-time commit stays unread despite earlier read acknowledgement',()=>{sql('candidate',`insert into public.messages(id,conversation_id,author_id,text,created_at) values('${uid(310)}','${PRIVATE}','${B}','Late older peer','2024-01-01');`,'sf_admin');assert.deepEqual(receipt('candidate',A,PRIVATE,[]).unread_message_ids,[OLD,uid(310)]);});
 check('metadata has one complete aggregate value beyond a simulated 1000-row REST cap',()=>{sql('candidate',`insert into public.messages(id,conversation_id,author_id,text) select ('00000000-0000-0000-0000-'||lpad((10000+i)::text,12,'0'))::uuid,'${PRIVATE}','${B}','Synthetic cap row' from generate_series(1,2005) i;`,'sf_admin');const r=receipt('candidate',A,PRIVATE,[]);assert.equal(r.complete,true);assert.equal(r.unread_message_ids.length,2007);assert.equal(new Set(r.unread_message_ids).size,2007);});
 check('complete known-read aggregate also exceeds 1000 rows without prefix marking or metadata truncation',()=>{const observed=Array.from({length:2005},(_,i)=>uid(10001+i));const saved=receipt('candidate',A,PRIVATE,observed,'mark_chat_messages_read');assert.equal(saved.read_message_ids.length,2005);const reloaded=receipt('candidate',A,PRIVATE,[]);assert.deepEqual(reloaded.read_message_ids,[]);assert.equal(reloaded.known_read_message_ids.length,2009);assert.deepEqual(reloaded.unread_message_ids,[OLD,uid(310)]);assert.equal(reloaded.known_read_message_ids.includes(GROUP_PEER),false);});
 check('idempotent migration replay preserves receipts/timestamps, existing policies/content/ACLs',()=>{const before=reads('candidate'),content=contents('candidate');sql('candidate',migration);assert.equal(reads('candidate'),before);assert.equal(contents('candidate'),content);assert.equal(policies('candidate'),oldPolicies);assert.equal(grants('candidate'),oldGrants);});
 clone('departed');seed('departed');sql('departed',migration);sql('departed',`delete from public.conversation_members where conversation_id='${PRIVATE}' and user_id='${A}';`,'sf_admin');
 check('fresh access departure rejects retries/read state without consuming any IDs',()=>{expectError('departed',as(A,`select public.mark_chat_messages_read('${A}','${PRIVATE}',${idsSql([M1])});`),'42501','Aktuell chattåtkomst');assert.equal(sql('departed','select count(*) from public.chat_message_reads;'),'0');sql('departed',`delete from public.stable_members where stable_id='${S}' and user_id='${A}';`,'sf_admin');expectError('departed',as(A,`select public.own_chat_read_state('${A}','${GROUP}',array[]::uuid[]);`),'42501','Aktuell chattåtkomst');});
 clone('inactive');seed('inactive');sql('inactive',migration);
 check('active profile plus non-deleted/non-banned Auth row required, including stale valid UID after profile removal',()=>{sql('inactive',`update auth.users set banned_until=now()+interval '1 hour' where id='${A}';`,'sf_admin');expectError('inactive',as(A,`select public.mark_chat_messages_read('${A}','${PRIVATE}',${idsSql([M1])});`),'42501','Aktivt eget konto');sql('inactive',`update auth.users set banned_until=null,deleted_at=now() where id='${A}';`,'sf_admin');expectError('inactive',as(A,`select public.own_chat_read_state('${A}','${PRIVATE}',array[]::uuid[]);`),'42501','Aktivt eget konto');sql('inactive',`update auth.users set deleted_at=null where id='${A}';`,'sf_admin');receipt('inactive',A,PRIVATE,[M1],'mark_chat_messages_read');sql('inactive',`delete from public.profiles where id='${A}';`,'sf_admin');expectError('inactive',as(A,`select public.own_chat_read_state('${A}','${PRIVATE}',array[]::uuid[]);`),'42501','Aktivt eget konto');assert.equal(sql('inactive','select count(*) from public.chat_message_reads;'),'0');});
 check('deleting a message removes only that own receipt by FK; other member receipts/content remain',()=>{const before=sql('candidate',`select text from public.messages where id='${M2}';`);sql('candidate',`delete from public.messages where id='${M1}';`,'sf_admin');assert.equal(sql('candidate',`select count(*) from public.chat_message_reads where message_id='${M1}';`),'0');assert.equal(sql('candidate',`select text from public.messages where id='${M2}';`),before);assert.equal(sql('candidate',`select count(*) from public.chat_message_reads where message_id='${M2}' and user_id='${A}';`),'1');});
 clone('drift');sql('drift','create table public.chat_message_reads(user_id uuid,message_id uuid,read_at text);');
 check('incompatible existing receipt table fails transaction before privilege/DDL adoption',()=>{const before=grants('drift');expectError('drift',migration,'55000','Befintlig tabell matchar inte');assert.equal(sql('drift',"select to_regprocedure('public.own_chat_read_state(uuid,uuid,uuid[])') is null;"),'t');assert.equal(grants('drift'),before);});
 clone('missing');sql('missing','drop table public.messages cascade;');
 check('missing required messages table fails migration atomically with no new receipt table',()=>{expectError('missing',migration,'42P01','does not exist');assert.equal(sql('missing',"select to_regclass('public.chat_message_reads') is null;"),'t');});
 // Independent sensitivity copies, not source edits: remove private gate or replace exact-ID insert with all peers.
 clone('negative_scope');seed('negative_scope');sql('negative_scope',negativeScope);
 check('negative scope baseline allows forbidden private stable-OR caller and is caught',()=>{let rejected=false;try{receipt('negative_scope',A,LEGACY_PRIVATE,[]);}catch{rejected=true;}assert.equal(rejected,false);});
 clone('negative_prefix');seed('negative_prefix');sql('negative_prefix',negativePrefix);
 check('negative prefix copy marks unseen peer history and exact subset assertion detects it',()=>{const r=receipt('negative_prefix',A,PRIVATE,[M1],'mark_chat_messages_read');assert.ok(!r.unread_message_ids.includes(M2)&&!r.unread_message_ids.includes(OLD));});
 report.status='PASS';report.check_count=checks.length;await writeFile(join(reports,'unread-result.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'PASS',checks:checks.length,migration_sha256:report.migration_sha256}));
}catch(error){report.status='FAIL';report.error=String(error.message);await writeFile(join(reports,'unread-result.json'),JSON.stringify(report,null,2)+'\n');throw error;}
finally{
 try{if(started||existsSync(join(data,'postmaster.pid')))command('pg_ctl',['-D',data,'-m','immediate','-w','stop']);}
 catch(error){report.status='FAIL';report.cleanup_error='[proposal unread] Owned PostgreSQL cluster did not stop.';throw error;}
 finally{await rm(directory,{recursive:true,force:true});report.cluster_removed=!existsSync(directory);await writeFile(join(reports,'unread-result.json'),JSON.stringify(report,null,2)+'\n');}
}
