import {
  systemPalette,
  systemStatus,
  systemGradients,
  systemTypography,
  systemSpacing,
  systemRadius,
  systemShadows,
} from '../design/system';

export const theme = {
  colors: {
    background: systemPalette.background,
    backgroundAlt: systemPalette.backgroundAlt,
    surface: systemPalette.surface,
    surfaceMuted: systemPalette.surfaceAlt,
    surfaceTint: systemPalette.surfaceTint,
    surfaceGlass: systemPalette.surfaceGlass,
    primaryText: systemPalette.textPrimary,
    secondaryText: systemPalette.textSecondary,
    mutedText: systemPalette.textMuted,
    disabledText: systemPalette.textDisabled,
    inverseText: systemPalette.textInverse,
    accent: systemPalette.accent,
    accentSoft: '#E7EFE6',
    primary: systemPalette.primary,
    info: systemPalette.info,
    warning: systemPalette.warning,
    error: systemPalette.error,
    success: systemPalette.success,
    badge: systemPalette.badge,
    border: systemPalette.border,
    borderMuted: systemPalette.borderMuted,
    divider: systemPalette.borderMuted,
    overlay: systemPalette.overlay,
    icon: systemPalette.icon,
  },
  status: {
    ...systemStatus,
  },
  tints: {
    accent: '#E7EFE6',
    primary: '#EDF3ED',
    info: '#EDF2F7',
    warning: '#FAF2E5',
    error: '#FBEDED',
    success: '#EDF5EE',
  },
  gradients: {
    background: systemGradients.background,
    weather: systemGradients.weather,
    action: systemGradients.action,
  },
  spacing: systemSpacing,
  typography: systemTypography,
  radii: systemRadius,
  borderRadius: systemRadius,
  shadows: {
    cardSoft: systemShadows.cardSoft,
    card: systemShadows.card,
    cardStrong: systemShadows.cardStrong,
  },
};
